// Programming Exercise 4.1
#include <iostream>

using std::cin;
using std::cout;
using std::endl;

const int ArrSize = 20;

int main() {
	char firstName[ArrSize], lastName[ArrSize], letter;
	int age;

	// Because a number was enteredin the main function, when cin reads the
    // number, it leaves the newline generated by the Enter key in the input
    // queue. Then, cin.getline() reads the newline as an empty line and assigns
    // a null string to the first name. cin.get() function solves this problem.
	// cin.get();	It was added in the main, which can solve the issue in each
    // function.
	cout << "What is your first name? ";
	cin.getline(firstName, ArrSize);
	cout << "What is your last name? ";
	cin.getline(lastName, ArrSize);
	cout << "What letter grade do you deserve? (A or B or C) ";
	cin >> letter;
	cout << "What is your age? ";
	(cin >> age).get();

	cout << "Name: " << lastName << ", " << firstName << endl;
	cout << "Grade: " << char(letter + 1) << endl;
	cout << "Age: " << age << endl;

    return 0;
}